# -*- coding: utf-8 -*-
"""Lab Task#1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/117rcyuff1DImAu-a2aqME8tP3TDGw5G-
"""

#Write a program to let the user enter a string of his own choice. 
#Check whether the given string is a palindrome or not. 

string = input("Enter string: ")
stack1=[]
for i in string:
       stack1.append(i)
reversed_text = ''
while len(stack1)!=0:
       reversed_text = reversed_text + stack1.pop()
print(reversed_text)
if string == reversed_text:
    print('The text is a palindrome.')
else:
    print('The text is not a palindrome.')

#Write a program to check the balanced parenthesis 
#in the expression or not using stack

string = input("Enter value: ")
stack1=[]
counter=0

for a in string:
  stack1.append(counter)
  if a=='('or a=='{' or a=='[':
    counter+=1
    stack1.append(a)
  else:
    if len(stack1)==0:
      print("Stack is full")
    elif a==')'or a=='}' or a==']':
      counter-=1
      stack1.pop()

if stack1==0:
  print("Balanced")
else:
  print("Not balanced")
print(counter)